name: jupyter test minimal
on:
  push:
    branches: 
jobs:
  jup-nb:
    runs-on: ubuntu-latest #use the latest ubuntu container image 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4 #use action to install python
        with:
          python-version: "3.9"
      - name: Install dependencies #requirements docs unable to read, hard installing dependencies 
        run: |
          pip install jupyter-book matplotlib numpy pandas ipywidgets notebook nbconvert p2j jupyterlab
          cp .github/workflows/import_test.py ./test_sc.py    

      - name: check health
        run: |
          #IMAGE=quay.io/rh_ee_keli/ucsls:stable-base-ope-latest
          IMAGE=quay.io/rh_ee_keli/ope:beta-image-template-NERC-test
          #IMAGE=quay.io/rh_ee_keli/ope:image-template-NERC-test
          docker pull $IMAGE
          docker image ls
          docker run -d --name test $IMAGE # use a different port number here
          echo "done running"
          sleep 5
          docker ps -a  
          docker stop test

      - name: verify sucess
        run: | 
          make pull-beta
          make run-beta &
          sleep 5
          container_id=$(docker ps -q | head -n 1)
          echo $container_id
          token=$(docker exec $container_id jupyter lab list 2>&1 | grep -o "token=[^ ]*" | cut -d= -f2)
          python3 .github/workflows/import_test.py $token